{
 "title": "Product_Catalog_ilya.lychkou",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "k8s_node", "query": { "query": "label_values(k8s_node)" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard info",
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "### 🛒 Product Catalog Service Dashboard\n\n- **Team Email:** [team-product-catalog@company.com](mailto:team-product-catalog@company.com)  \n- **Slack Channel:** [#product-catalog-alerts](https://slack.com/app_redirect?channel=product-catalog-alerts)\n- **Phone:** +238472983472938\n\n---\n\n💬 For issues, ping us on Slack, call or send an email.\n"
   }
  },
  {
   "title": "Status code (Stats)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\n  rate(http_requests_total{path!=\"/metrics\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics for instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance"
  },
  {
   "title": "SLI (last 28d)",
   "type": "stat",
   "description": "SLI (last 28d)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum by (instance) (\n      rate(http_requests_total{status=~\"2..\", instance=~\"$instance:.*\", k8s_node=~\"$k8s_node\"}[28d])\n    )\n    /\n    sum by (instance) (\n      rate(http_requests_total{instance=~\"$instance:.*\", k8s_node=~\"$k8s_node\"}[28d])\n    )\n  ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Number of sucessfull requests / Number of all requests",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( sum by (instance) (\n  rate(http_requests_total{status=~\"2..\",instance=~\"$instance:.*\", k8s_node=~\"$k8s_node\"}[$__rate_interval])\n)\n/\nsum by (instance) (\n  rate(http_requests_total{instance=~\"$instance:.*\", k8s_node=~\"$k8s_node\"}[$__rate_interval])\n)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Second by path, status",
   "type": "timeseries",
   "description": "RPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"product_catalog_app\",path!=\"/metrics\",instance=~\"$instance:.*\",status=\"200\", k8s_node=~\"$k8s_node\"}[$__rate_interval])",
     "legendFormat": "{{path}}:{{status}}"
    }
   ]
  },
  {
   "title": "Errors Per Second - 4xx, 5xx",
   "type": "timeseries",
   "description": "RPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"product_catalog_app\",path!=\"/metrics\",instance=~\"$instance:.*\",status=~\"4..|5..\", k8s_node=~\"$k8s_node\"}[$__rate_interval])",
     "legendFormat": "{{path}}:{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "RPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by (le, path, status) (\n    rate(http_requests_latency_seconds_bucket{\n      path!=\"/metrics\",\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "p99 {{status}}: {{path}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (go_memstats_heap_sys_bytes{instance=~\"$instance:.*\", k8s_node=~\"$k8s_node\"} / 1024 / 1024)",
     "legendFormat": "go_memstats_heap_sys_megabutes"
    }
   ]
  },
  {
   "title": "Metrics per node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(k8s_node) (go_memstats_heap_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency distribution over nodes ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum by(le, k8s_node) (rate(http_requests_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS per k8s node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(k8s_node) (rate(http_requests_total{path!=\"/metrics\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}