# Здесь нужно настроить сбор метрик, чтобы увидеть их в grafana.
# Не листайте вниз к решению, пока не настроите сбор самостоятельно.
# Вам понадобится собирать метрики с двух реплик приложения.
# Имя контейнера - dns имя внутри docker сети, по которому нужно ходить за метриками.
# Метрики доступны на порту 8080 для обоих реплик сервиса.



global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product_catalog_app'
    static_configs:
      - targets: ['product-catalog-replica-1:8080']
        labels:
          k8s_node: 'replica-1'
      - targets: ['product-catalog-replica-2:8080']
        labels:
          k8s_node: 'replica-2'






















































































































































































#global:
#  scrape_interval: 10s
#  scrape_timeout: 1s
#
#scrape_configs:
#  - job_name: product-catalog-01
#    static_configs:
#      - targets: ['product-catalog-01:8080']
#        labels:
#          k8s_node: 'node-01'
#  - job_name: product-catalog-02
#    static_configs:
#      - targets: ['product-catalog-02:8080']
#        labels:
#          k8s_node: 'node-02'